### ISSUE TITLE
Перепутаны значения 10 и 12 (у юр. лиц 10, у физ. лиц 12)

### ISSUE THREAD

**Issue by kashinss** [devsergeev/inn-validator#4]
https://github.com/devsergeev/inn-validator/blob/1826d6d6d68a826cf654353cf29010bce673cde8/src/InnValidator.php#L16

**Comment by devsergeev** [comment]
Спасибо за замечание, исправлено
https://github.com/devsergeev/inn-validator/releases/tag/2.0.2
